version: '3'
services:
        mysql:
                image: mysql_img:latest
                ports:
                        - "3306:3306"
                volumes:
                        - /home/cmoyah/data/mysql:/var/lib/mysql
                restart: always
                environment:
                      MYSQL_ROOT_PASSWORD: password

        wordpress:
                depends_on:
                        - mysql
                image: wordpress_img:latest
                ports:
                        - "9000:9000"
                restart: always
                links:
                        - mysql
                volumes:
                        - /home/cmoyah/data/wordpress:/var/www/html
        nginx:
                image: nginx_img:latest
                ports:
                        - "80:80"
                        - "443:443"
                restart: always
                links:
                        - wordpress
                volumes:
                        - /home/cmoyah/data/wordpress:/var/www/html
